In [42]:
import sys

def MazeReader(file_path):
    with open(file_path) as f:
        lines=f.readlines()
        #remove the '\n'，replace with ''
        for i in range(len(lines)):
            lines[i]=lines[i].replace('\n','')
            
    return lines
    
def fromchart(c):
    if c=='#':
        a=0
    elif c=='.':
        a=1
    elif c=='o':
        a=2
    elif c=='*':
        a=3
    else:
        print('IllegalArgumentException')
        sys.exit()
    return a

def draw_raw(lines):
    print('maze:')
    for line in lines:
        print(line)

In [43]:
import numpy as np
import sys

file_path='maze-2.txt'

lines=MazeReader(file_path)

draw_raw(lines)

#genernate a matrix of the graph
a=len(lines)
b=len(lines[a-1])
maze=5*np.ones([a,b])
#print(maze)

for i in range(a):
    for j in range(b):
        c=lines[i][j]
        maze[i,j]=fromchart(c)
#print(maze)


maze:
############
#.#........#
#.#.######.#
#.#....#...#
#.###.*#.#.#
#...####.#.#
#.#.#..#.#.#
#.#.#.##.#.#
#o#......#.#
############


In [76]:
print(maze)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 1. 1. 1. 1. 0. 1. 1. 1. 0.]
 [0. 1. 0. 0. 0. 1. 3. 0. 1. 0. 1. 0.]
 [0. 1. 1. 1. 0. 0. 0. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 0. 1. 0. 1. 0.]
 [0. 2. 0. 1. 1. 1. 1. 1. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
